name: "Yuriy Yunikov | Java and Android Software Engineer"
description: "Personal Web-Site"
url: http://yunikov.com
author: Yuriy Yunikov

include: ['_pages']
exclude: ["node_modules", "Gruntfile.js", "package.json"]

markdown: rdiscount
permalink: /blog/:categories/:year/:month/:day/:title/
relative_permalinks: false

paginate: 5
paginate_path: "/blog/all/page:num/"

encoding: UTF-8

disqus: yunikovcom