name: "Yuriy Yunikov | Java and Android Software Engineer"
description: "Personal Web-Site"

exclude: ["node_modules", "Gruntfile.js", "package.json"]

markdown: rdiscount
permalink: /blog/:categories/:year/:month/:day/:title/

encoding: UTF-8

paginate: 5

disqus: yunikovcom