name: "Yuriy Yunikov | Java and Android Software Engineer"
description: "Personal Web-Site"

exclude: ["node_modules", "Gruntfile.js", "package.json"]

markdown: rdiscount
permalink: /blog/categories/:categories/:year/:month/:day/:title/

paginate: 5
paginate_path: "/blog/categories/all/page:num/"

encoding: UTF-8

disqus: yunikovcom