name: "Yuriy Yunikov | Java and Android Software Engineer"
description: "Personal Web-Site"
url: https://yunikov.com
author: Yuriy Yunikov
person: Yuriy Yunikov

include: ['_pages']
exclude: ["node_modules", "gulpfile.js", "package.json", vendor]

encoding: UTF-8
dynamicPages: ['applications', 'presentations']