name: "Yuriy Yunikov | Java and Android Software Engineer"
description: "Personal Web-Site"

exclude: ["node_modules", "README.md", "Gruntfile.js", "package.json"]

markdown: rdiscount
permalink: pretty

encoding: UTF-8